import { useState } from 'react';
import { format } from 'date-fns';
import type { MatchReport } from '../../types';
import { POSITION_LABELS } from '../../types';

interface Props {
  report: MatchReport;
}

function ReportSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="border-t border-court-800 pt-4">
      <h4 className="text-xs font-semibold text-chalk-500 mb-2">{title}</h4>
      {children}
    </div>
  );
}

function Highlight({ icon, text }: { icon: string; text: string }) {
  return (
    <div className="flex items-start gap-2 text-sm text-chalk-300">
      <span className="shrink-0 text-navy-700">{icon}</span>
      <span>{text}</span>
    </div>
  );
}

export default function MatchReportCard({ report }: Props) {
  const [copied, setCopied] = useState(false);

  // Build plain-text version for export/copy
  function buildPlainText(): string {
    const lines: string[] = [];
    lines.push('VOLLEYVISION MATCH REPORT');
    lines.push(`Generated: ${format(new Date(report.generatedAt), 'PPP p')}`);
    lines.push('');
    lines.push('RESULT');
    lines.push(report.result.resultText);
    if (report.result.setScores.length > 0) {
      const sets = report.result.setScores.map((s) => `${s.home}–${s.away}`).join('  ');
      lines.push(`Set Scores: ${sets}`);
    }
    if (report.topPerformer) {
      const p = report.topPerformer.player;
      lines.push('');
      lines.push('TOP PERFORMER');
      lines.push(`#${p.jerseyNumber} ${p.firstName} ${p.lastName} (${POSITION_LABELS[p.position]})`);
      const stats = [];
      if (report.topPerformer.kills > 0) stats.push(`${report.topPerformer.kills} Kills`);
      if (report.topPerformer.aces > 0) stats.push(`${report.topPerformer.aces} Aces`);
      if (report.topPerformer.blocks > 0) stats.push(`${report.topPerformer.blocks} Blocks`);
      if (report.topPerformer.digs > 0) stats.push(`${report.topPerformer.digs} Digs`);
      if (report.topPerformer.assists > 0) stats.push(`${report.topPerformer.assists} Assists`);
      lines.push(stats.join(' · '));
    }
    if (report.attack.attempts > 0) {
      lines.push('');
      lines.push('ATTACK');
      if (report.attack.killRate != null) lines.push(`Kill Rate: ${report.attack.killRate}%`);
      if (report.attack.hittingPct != null) lines.push(`Hitting %: ${report.attack.hittingPct >= 0 ? '+' : ''}${(report.attack.hittingPct * 100).toFixed(1)}%`);
    }
    if (report.serve.attempts > 0) {
      lines.push('');
      lines.push('SERVE');
      lines.push(`${report.serve.aces} Aces from ${report.serve.attempts} serves`);
      if (report.serve.aceRate != null) lines.push(`Ace Rate: ${report.serve.aceRate}%`);
    }
    if (report.momentum) {
      lines.push('');
      lines.push('MOMENTUM');
      lines.push(`Longest Run: ${report.momentum.longestRun} points (${report.momentum.longestRunTeam})`);
      lines.push(`Lead Changes: ${report.momentum.leadChanges}`);
    }
    if (report.bestRotation) {
      lines.push('');
      lines.push('BEST ROTATION');
      lines.push(`Rotation ${report.bestRotation.rotation} — Net +${report.bestRotation.net}${report.bestRotation.efficiency != null ? ` (${report.bestRotation.efficiency}% efficiency)` : ''}`);
    }
    if (report.heatMapHighlight) {
      lines.push('');
      lines.push('HEAT MAP INSIGHT');
      lines.push(report.heatMapHighlight);
    }
    lines.push('');
    lines.push('─'.repeat(40));
    lines.push('Generated by VolleyVision');
    return lines.join('\n');
  }

  function handleCopy() {
    navigator.clipboard.writeText(buildPlainText()).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  const { result, topPerformer, momentum, attack, serve, heatMapHighlight, bestRotation } = report;

  return (
    <div className="card overflow-hidden">
      {/* Header */}
      <div className="bg-court-900 border-b border-court-800 px-5 py-4 flex items-center justify-between gap-3">
        <div>
          <div className="flex items-center gap-2 mb-0.5">
            <span className="text-xs font-semibold text-navy-700">Match Report</span>
          </div>
          <p className="text-xs text-chalk-500">
            Generated {format(new Date(report.generatedAt), 'PPP · p')}
          </p>
        </div>
        <button
          onClick={handleCopy}
          className="text-xs font-medium px-3 py-1.5 rounded-lg bg-court-800 hover:bg-court-700 border border-court-700 text-chalk-300 transition-colors shrink-0"
        >
          {copied ? '✓ Copied' : '↗ Copy Report'}
        </button>
      </div>

      <div className="px-5 py-4 space-y-4">
        {/* Result */}
        <div>
          <p className={`text-lg font-bold leading-snug ${
            result.winner === 'home' ? 'text-navy-700' : result.winner === 'away' ? 'text-chalk-300' : 'text-chalk-100'
          }`}>
            {result.resultText}
          </p>
          {result.setScores.length > 0 && (
            <div className="flex gap-2 mt-2 flex-wrap">
              {result.setScores.map((s) => {
                const homeWon = s.home > s.away;
                return (
                  <span
                    key={s.set}
                    className={`text-xs font-mono px-2 py-0.5 rounded border ${
                      homeWon
                        ? 'text-navy-700 border-spike-500/30 bg-spike-500/10'
                        : 'text-chalk-400 border-court-700 bg-court-800'
                    }`}
                  >
                    S{s.set}: {s.home}–{s.away}
                  </span>
                );
              })}
            </div>
          )}
        </div>

        {/* Top Performer */}
        {topPerformer && (
          <ReportSection title="Top Performer">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-spike-500/20 border border-spike-500/30 flex items-center justify-center shrink-0">
                <span className="font-mono font-bold text-navy-700 text-sm">#{topPerformer.player.jerseyNumber}</span>
              </div>
              <div>
                <div className="font-semibold text-chalk-100">
                  {topPerformer.player.firstName} {topPerformer.player.lastName}
                  <span className="text-chalk-500 text-xs ml-2">{POSITION_LABELS[topPerformer.player.position]}</span>
                </div>
                <div className="text-xs text-chalk-400 mt-0.5 flex gap-3 flex-wrap">
                  {topPerformer.kills > 0 && <span><span className="font-mono font-bold text-chalk-200">{topPerformer.kills}</span> Kills</span>}
                  {topPerformer.aces > 0 && <span><span className="font-mono font-bold text-chalk-200">{topPerformer.aces}</span> Aces</span>}
                  {topPerformer.blocks > 0 && <span><span className="font-mono font-bold text-chalk-200">{topPerformer.blocks}</span> Blocks</span>}
                  {topPerformer.digs > 0 && <span><span className="font-mono font-bold text-chalk-200">{topPerformer.digs}</span> Digs</span>}
                  {topPerformer.assists > 0 && <span><span className="font-mono font-bold text-chalk-200">{topPerformer.assists}</span> Assists</span>}
                </div>
              </div>
            </div>
          </ReportSection>
        )}

        {/* Key Insights */}
        <ReportSection title="Key Insights">
          <div className="space-y-1.5">
            {attack.attempts > 0 && attack.killRate != null && (
              <Highlight
                icon="⚡"
                text={`Attack kill rate ${attack.killRate}% from ${attack.attempts} attempts (${attack.kills} kills, ${attack.errors} errors)`}
              />
            )}
            {attack.hittingPct != null && (
              <Highlight
                icon="📊"
                text={`Hitting percentage ${attack.hittingPct >= 0 ? '+' : ''}${(attack.hittingPct * 100).toFixed(1)}%`}
              />
            )}
            {serve.attempts > 0 && serve.aceRate != null && (
              <Highlight
                icon="🎯"
                text={`${serve.aces} aces from ${serve.attempts} serves (${serve.aceRate}% ace rate)`}
              />
            )}
            {momentum && momentum.longestRun >= 3 && (
              <Highlight
                icon="🔥"
                text={`${momentum.longestRunTeam} went on a ${momentum.longestRun}-point scoring run`}
              />
            )}
            {momentum && momentum.leadChanges > 0 && (
              <Highlight
                icon="⚖️"
                text={`Lead changed hands ${momentum.leadChanges} time${momentum.leadChanges !== 1 ? 's' : ''} — competitive match`}
              />
            )}
            {bestRotation && (
              <Highlight
                icon="🔄"
                text={`Best rotation: Rotation ${bestRotation.rotation} with +${bestRotation.net} net points${bestRotation.efficiency != null ? ` (${bestRotation.efficiency}% efficiency)` : ''}`}
              />
            )}
            {heatMapHighlight && (
              <Highlight icon="🗺️" text={heatMapHighlight} />
            )}
            {/* Fallback if no events yet */}
            {attack.attempts === 0 && serve.attempts === 0 && !momentum && !heatMapHighlight && (
              <p className="text-sm text-chalk-500">Record events during the match to generate insights.</p>
            )}
          </div>
        </ReportSection>

        {/* Attack + Serve summary row */}
        {(attack.attempts > 0 || serve.attempts > 0) && (
          <ReportSection title="Performance Summary">
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              {attack.attempts > 0 && (
                <>
                  <div className="text-center">
                    <p className="font-mono text-xl font-bold text-chalk-100">{attack.kills}</p>
                    <p className="text-xs text-chalk-500 mt-0.5">Kills</p>
                  </div>
                  <div className="text-center">
                    <p className={`font-mono text-xl font-bold ${attack.hittingPct != null && attack.hittingPct >= 0.25 ? 'text-success' : attack.hittingPct != null && attack.hittingPct >= 0 ? 'text-navy-700' : 'text-error'}`}>
                      {attack.hittingPct != null ? `${attack.hittingPct >= 0 ? '+' : ''}${(attack.hittingPct * 100).toFixed(0)}%` : '—'}
                    </p>
                    <p className="text-xs text-chalk-500 mt-0.5">Hit %</p>
                  </div>
                </>
              )}
              {serve.attempts > 0 && (
                <>
                  <div className="text-center">
                    <p className="font-mono text-xl font-bold text-chalk-100">{serve.aces}</p>
                    <p className="text-xs text-chalk-500 mt-0.5">Aces</p>
                  </div>
                  <div className="text-center">
                    <p className="font-mono text-xl font-bold text-chalk-100">
                      {serve.aceRate != null ? `${serve.aceRate}%` : '—'}
                    </p>
                    <p className="text-xs text-chalk-500 mt-0.5">Ace Rate</p>
                  </div>
                </>
              )}
            </div>
          </ReportSection>
        )}
      </div>
    </div>
  );
}
